/*
** ###################################################################
**     This code is generated by the Device Initialization Tool.
**     It is overwritten during code generation.
**     USER MODIFICATION ARE PRESERVED ONLY INSIDE INTERRUPT SERVICE ROUTINES
**     OR EXPLICITLY MARKED SECTIONS
**
**     Project   : DeviceInitialization
**     Processor : MK60DN512ZVLQ10
**     Version   : Component 01.000, Driver 01.02, CPU db: 3.00.001
**     Datasheet : K60P144M100SF2RM, Rev. 4, 1 Mar 2011
**     Date/Time : 2012-06-28, 09:25, # CodeGen: 10
**     Abstract  :
**
**     Contents  :
**         Function "MCU_init" initializes selected peripherals
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################
*/

/* MODULE MCUinit */

#define PE_MCUINIT

#include <MK60DZ10.h>                  /* I/O map for MK60DN512ZVLQ10 */
#include "MCUinit.h"

typedef void (*const tIsrFunc)(void);
typedef struct {
  uint32_t * __ptr;
  tIsrFunc __fun[119];
} tVectorTable;

/* User declarations and definitions */
/*   Code, declarations and definitions here will be preserved during code generation */
/* End of user declarations and definitions */

/*
** ===================================================================
**     Method      :  Cpu_SetBASEPRI (component MK60N512LQ100)
**
**     Description :
**         This method sets the BASEPRI core register.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
/*lint -save  -e586 -e950 Disable MISRA rule (2.1,1.1) checking. */
#ifdef _lint
  #define Cpu_SetBASEPRI(Level)  /* empty */
#else
asm void Cpu_SetBASEPRI(register uint32_t Level) {
  MSR BASEPRI,R0;
  MOV PC,LR
}
#endif
/*lint -restore Enable MISRA rule (2.1,1.1) checking. */
/*
** ===================================================================
**     Method      :  __init_hardware (component MK60N512LQ100)
**
**     Description :
**         Initialization code for CPU core and a clock source.
** ===================================================================
*/
extern uint32_t __vector_table[];
void __init_hardware(void)
{
  /*** ### MK60DN512ZVLQ10 "Cpu" init code ... ***/
  /*** PE initialization code after reset ***/
  SCB_VTOR = (uint32_t)__vector_table; /* Set the interrupt vector table position */
  /* Disable the WDOG module */
  /* WDOG_UNLOCK: WDOGUNLOCK=0xC520 */
  WDOG_UNLOCK = (uint16_t)0xC520U;     /* Key 1 */
  /* WDOG_UNLOCK : WDOGUNLOCK=0xD928 */
  WDOG_UNLOCK  = (uint16_t)0xD928U;    /* Key 2 */
  /* WDOG_STCTRLH: DISTESTWDOG=0,BYTESEL=0,TESTSEL=0,TESTWDOG=0,STNDBYEN=1,WAITEN=1,STOPEN=1,DBGEN=0,ALLOWUPDATE=1,WINEN=0,IRQRSTEN=0,CLKSRC=1,WDOGEN=0 */
  WDOG_STCTRLH = (uint16_t)0x01D2U;                  
  /* System clock initialization */
  /* SIM_CLKDIV1: OUTDIV1=0,OUTDIV2=1,OUTDIV3=3,OUTDIV4=3 */
  SIM_CLKDIV1 = (uint32_t)0x01330000UL; /* Update system prescalers */
  /* SIM_CLKDIV2: USBDIV=1,USBFRAC=0 */
  SIM_CLKDIV2 = (uint32_t)((SIM_CLKDIV2 & (uint32_t)~0x0DUL) | (uint32_t)0x02UL); /* Update USB clock prescalers */
  /* SIM_SOPT2: PLLFLLSEL=1 */
  SIM_SOPT2 |= (uint32_t)0x00010000UL; /* Select PLL as a clock source for various peripherals */
  /* SIM_SOPT1: OSC32KSEL=0 */
  SIM_SOPT1 &= (uint32_t)~0x00080000UL; /* System oscillator drives 32 kHz clock for various peripherals */
  /* Switch to FBE Mode */
  /* OSC_CR: ERCLKEN=0,EREFSTEN=0,SC2P=0,SC4P=0,SC8P=0,SC16P=0 */
  OSC_CR = (uint8_t)0x00U;                             
  /* SIM_SOPT2: MCGCLKSEL=0 */
  SIM_SOPT2 &= (uint32_t)~0x01UL;                      
  /* MCG_C2: RANGE=2,HGO=0,EREFS=0,LP=0,IRCS=0 */
  MCG_C2 = (uint8_t)0x20U;                             
  /* MCG_C1: CLKS=2,FRDIV=5,IREFS=0,IRCLKEN=1,IREFSTEN=0 */
  MCG_C1 = (uint8_t)0xAAU;                             
  /* MCG_C4: DMX32=0,DRST_DRS=0 */
  MCG_C4 &= (uint8_t)~(uint8_t)0xE0U;                           
  /* MCG_C5: PLLCLKEN=0,PLLSTEN=0,PRDIV=0x0F */
  MCG_C5 = (uint8_t)0x0FU;                             
  /* MCG_C6: LOLIE=0,PLLS=0,CME=0,VDIV=8 */
  MCG_C6 = (uint8_t)0x08U;                             
  while((MCG_S & MCG_S_IREFST_MASK) != 0x00U) { /* Check that the source of the FLL reference clock is the external reference clock. */
  }
  while((MCG_S & 0x0CU) != 0x08U) {    /* Wait until external reference clock is selected as MCG output */
  }
  /* Switch to PBE Mode */
  /* OSC_CR: ERCLKEN=0,EREFSTEN=0,SC2P=0,SC4P=0,SC8P=0,SC16P=0 */
  OSC_CR = (uint8_t)0x00U;                             
  /* SIM_SOPT2: MCGCLKSEL=0 */
  SIM_SOPT2 &= (uint32_t)~0x01UL;                      
  /* MCG_C1: CLKS=2,FRDIV=5,IREFS=0,IRCLKEN=1,IREFSTEN=0 */
  MCG_C1 = (uint8_t)0xAAU;                             
  /* MCG_C2: RANGE=2,HGO=0,EREFS=0,LP=0,IRCS=0 */
  MCG_C2 = (uint8_t)0x20U;                             
  /* MCG_C5: PLLCLKEN=0,PLLSTEN=0,PRDIV=0x0F */
  MCG_C5 = (uint8_t)0x0FU;                             
  /* MCG_C6: LOLIE=0,PLLS=1,CME=0,VDIV=8 */
  MCG_C6 = (uint8_t)0x48U;                             
  while((MCG_S & 0x0CU) != 0x08U) {    /* Wait until external reference clock is selected as MCG output */
  }
  /* Switch to PEE Mode */
  /* OSC_CR: ERCLKEN=0,EREFSTEN=0,SC2P=0,SC4P=0,SC8P=0,SC16P=0 */
  OSC_CR = (uint8_t)0x00U;                             
  /* SIM_SOPT2: MCGCLKSEL=0 */
  SIM_SOPT2 &= (uint32_t)~0x01UL;                      
  /* MCG_C1: CLKS=0,FRDIV=5,IREFS=0,IRCLKEN=1,IREFSTEN=0 */
  MCG_C1 = (uint8_t)0x2AU;                             
  /* MCG_C2: RANGE=2,HGO=0,EREFS=0,LP=0,IRCS=0 */
  MCG_C2 = (uint8_t)0x20U;                             
  /* MCG_C5: PLLCLKEN=0,PLLSTEN=0,PRDIV=0x0F */
  MCG_C5 = (uint8_t)0x0FU;                             
  /* MCG_C6: LOLIE=0,PLLS=1,CME=0,VDIV=8 */
  MCG_C6 = (uint8_t)0x48U;                             
  while((MCG_S & 0x0CU) != 0x0CU) {    /* Wait until output of the PLL is selected */
  }
  while((MCG_S & MCG_S_LOCK_MASK) == 0x00U) { /* Wait until locked */
  }
  /* SIM_SCGC5: PORTE=1,PORTD=1,PORTC=1,PORTB=1,PORTA=1 */
  SIM_SCGC5 |= (uint32_t)0x3E00UL;     /* Enable clock gate for ports to enable pin routing */
}

/*
** ===================================================================
**     Method      :  MCU_init (component MK60N512LQ100)
**
**     Description :
**         Device initialization code for selected peripherals.
** ===================================================================
*/
void MCU_init(void)
{
  /* PORTA_PCR4: ISF=0,MUX=7 */
  PORTA_PCR4 = (uint32_t)((PORTA_PCR4 & (uint32_t)~0x01000000UL) | (uint32_t)0x0700UL);
  /* PORTA_PCR2: ISF=0,MUX=7 */
  PORTA_PCR2 = (uint32_t)((PORTA_PCR2 & (uint32_t)~0x01000000UL) | (uint32_t)0x0700UL);
  /* PORTA_PCR1: ISF=0,MUX=7 */
  PORTA_PCR1 = (uint32_t)((PORTA_PCR1 & (uint32_t)~0x01000000UL) | (uint32_t)0x0700UL);
  /* PORTA_PCR0: ISF=0,MUX=7 */
  PORTA_PCR0 = (uint32_t)((PORTA_PCR0 & (uint32_t)~0x01000000UL) | (uint32_t)0x0700UL);
  /* PORTA_PCR3: ISF=0,MUX=7 */
  PORTA_PCR3 = (uint32_t)((PORTA_PCR3 & (uint32_t)~0x01000000UL) | (uint32_t)0x0700UL);
  /* PORTA_PCR5: ISF=0,MUX=7 */
  PORTA_PCR5 = (uint32_t)((PORTA_PCR5 & (uint32_t)~0x01000000UL) | (uint32_t)0x0700UL);
  /* SIM_SOPT6: RSTFLTEN=0,RSTFLTSEL=0 */
  SIM_SOPT6 = (uint32_t)0x00UL;        /* Set reset pin filter */
  /* SIM_SCGC7: MPU=1 */
  SIM_SCGC7 |= (uint32_t)0x04UL;                       
  /* Initialization of the MPU module */
  /* MPU_CESR: SPERR=0,VLD=0 */
  MPU_CESR &= (uint32_t)~0xF8000001UL;                      
  /* MPU_RGDAAC0: M5RE=0,M5WE=0,M4RE=0,M4WE=0,M3SM=3,M3UM=0,M2SM=3,M2UM=7,M1SM=3,M1UM=7,M0SM=3,M0UM=7 */
  MPU_RGDAAC0 = (uint32_t)((MPU_RGDAAC0 & (uint32_t)~0x0F1C0000UL) | (uint32_t)0x0061F7DFUL);
  /* MPU_RGD1_WORD3: VLD=0 */
  MPU_RGD1_WORD3 &= (uint32_t)~0x01UL;                      
  /* MPU_RGD2_WORD3: VLD=0 */
  MPU_RGD2_WORD3 &= (uint32_t)~0x01UL;                      
  /* MPU_RGD3_WORD3: VLD=0 */
  MPU_RGD3_WORD3 &= (uint32_t)~0x01UL;                      
  /* MPU_RGD4_WORD3: VLD=0 */
  MPU_RGD4_WORD3 &= (uint32_t)~0x01UL;                      
  /* MPU_RGD5_WORD3: VLD=0 */
  MPU_RGD5_WORD3 &= (uint32_t)~0x01UL;                      
  /* MPU_RGD6_WORD3: VLD=0 */
  MPU_RGD6_WORD3 &= (uint32_t)~0x01UL;                      
  /* MPU_RGD7_WORD3: VLD=0 */
  MPU_RGD7_WORD3 &= (uint32_t)~0x01UL;                      
  /* MPU_RGD8_WORD3: VLD=0 */
  MPU_RGD8_WORD3 &= (uint32_t)~0x01UL;                      
  /* MPU_RGD9_WORD3: VLD=0 */
  MPU_RGD9_WORD3 &= (uint32_t)~0x01UL;                      
  /* MPU_RGD10_WORD3: VLD=0 */
  MPU_RGD10_WORD3 &= (uint32_t)~0x01UL;                      
  /* MPU_RGD11_WORD3: VLD=0 */
  MPU_RGD11_WORD3 &= (uint32_t)~0x01UL;                      
  /* MPU_CESR: SPERR=0,VLD=1 */
  MPU_CESR = (uint32_t)((MPU_CESR & (uint32_t)~0xF8000000UL) | (uint32_t)0x01UL);
  /* Initialization of the PMC module */
  /* PMC_LVDSC1: LVDACK=1,LVDIE=0,LVDRE=1,LVDV=0 */
  PMC_LVDSC1 = (uint8_t)((PMC_LVDSC1 & (uint8_t)~(uint8_t)0x23U) | (uint8_t)0x50U);
  /* PMC_LVDSC2: LVWACK=1,LVWIE=0,LVWV=0 */
  PMC_LVDSC2 = (uint8_t)((PMC_LVDSC2 & (uint8_t)~(uint8_t)0x23U) | (uint8_t)0x40U);
  /* PMC_REGSC: TRAMPO=0,BGBE=0 */
  PMC_REGSC &= (uint8_t)~(uint8_t)0x13U;                           
  /* MC_PMPROT: AVLP=0,ALLS=0,AVLLS3=0,AVLLS2=0,AVLLS1=0 */
  MC_PMPROT = (uint8_t)0x00U;          /* Setup Power mode protection register */
  /* Common initialization of the CPU registers */
  /* NVICIP62: PRI62=0 */
  NVICIP62 = (uint8_t)0x00U;                             
  /* NVICIP63: PRI63=0 */
  NVICIP63 = (uint8_t)0x00U;                             
  /* NVICIP85: PRI85=0 */
  NVICIP85 = (uint8_t)0x00U;                             
  /* NVICIP68: PRI68=0x80 */
  NVICIP68 = (uint8_t)0x80U;                             
  /* NVICIP69: PRI69=0x30 */
  NVICIP69 = (uint8_t)0x30U;                             
  /* NVICIP70: PRI70=0x40 */
  NVICIP70 = (uint8_t)0x40U;                             
  /* NVICIP71: PRI71=0 */
  NVICIP71 = (uint8_t)0x00U;                             
  /* NVICIP87: PRI87=0x60 */
  NVICIP87 = (uint8_t)0x60U;                             
  /* NVICIP89: PRI89=0x40 */
  NVICIP89 = (uint8_t)0x40U;                             
  /* NVICIP27: PRI27=0 */
  NVICIP27 = (uint8_t)0x00U;                             
  /* NVICIP49: PRI49=0x30 */
  NVICIP49 = (uint8_t)0x30U;                             
  /* NVICIP50: PRI50=0 */
  NVICIP50 = (uint8_t)0x00U;                             
  /* NVICIP20: PRI20=0 */
  NVICIP20 = (uint8_t)0x00U;                             
  /* PORTD_PCR4: ISF=0,MUX=4 */
  PORTD_PCR4 = (uint32_t)((PORTD_PCR4 & (uint32_t)~0x01000300UL) | (uint32_t)0x0400UL);
  /* PORTA_PCR8: ISF=0,MUX=3 */
  PORTA_PCR8 = (uint32_t)((PORTA_PCR8 & (uint32_t)~0x01000400UL) | (uint32_t)0x0300UL);
  /* PORTA_PCR9: ISF=0,MUX=3 */
  PORTA_PCR9 = (uint32_t)((PORTA_PCR9 & (uint32_t)~0x01000400UL) | (uint32_t)0x0300UL);
  /* PORTC_PCR5: ISF=0,MUX=4 */
  PORTC_PCR5 = (uint32_t)((PORTC_PCR5 & (uint32_t)~0x01000300UL) | (uint32_t)0x0400UL);
  /* PORTA_PCR10: ISF=0,IRQC=0,MUX=1,ODE=1 */
  PORTA_PCR10 = (uint32_t)((PORTA_PCR10 & (uint32_t)~0x010F0600UL) | (uint32_t)0x0120UL);
  /* PORTA_PCR11: ISF=0,IRQC=0x0A,MUX=1,ODE=1 */
  PORTA_PCR11 = (uint32_t)((PORTA_PCR11 & (uint32_t)~0x01050600UL) | (uint32_t)0x000A0120UL);
  /* PORTA_PCR12: ISF=0,IRQC=0,MUX=1,ODE=1 */
  PORTA_PCR12 = (uint32_t)((PORTA_PCR12 & (uint32_t)~0x010F0600UL) | (uint32_t)0x0120UL);
  /* PORTA_PCR13: ISF=0,MUX=1,ODE=1 */
  PORTA_PCR13 = (uint32_t)((PORTA_PCR13 & (uint32_t)~0x01000600UL) | (uint32_t)0x0120UL);
  /* PORTA_DFCR: CS=0 */
  PORTA_DFCR &= (uint32_t)~0x01UL;                      
  /* PORTA_DFWR: FILT=0 */
  PORTA_DFWR &= (uint32_t)~0x1FUL;                      
  /* PORTA_PCR14: ISF=0,MUX=1 */
  PORTA_PCR14 = (uint32_t)((PORTA_PCR14 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTA_PCR15: ISF=0,MUX=1 */
  PORTA_PCR15 = (uint32_t)((PORTA_PCR15 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTA_PCR16: ISF=0,MUX=1 */
  PORTA_PCR16 = (uint32_t)((PORTA_PCR16 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTA_PCR17: ISF=0,MUX=1 */
  PORTA_PCR17 = (uint32_t)((PORTA_PCR17 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTA_PCR26: ISF=0,MUX=1 */
  PORTA_PCR26 = (uint32_t)((PORTA_PCR26 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTA_PCR28: ISF=0,MUX=1 */
  PORTA_PCR28 = (uint32_t)((PORTA_PCR28 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTB_DFCR: CS=0 */
  PORTB_DFCR &= (uint32_t)~0x01UL;                      
  /* PORTB_DFWR: FILT=0 */
  PORTB_DFWR &= (uint32_t)~0x1FUL;                      
  /* PORTB_PCR0: ISF=0,MUX=1 */
  PORTB_PCR0 = (uint32_t)((PORTB_PCR0 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTB_PCR1: ISF=0,MUX=1 */
  PORTB_PCR1 = (uint32_t)((PORTB_PCR1 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTB_PCR2: ISF=0,MUX=1 */
  PORTB_PCR2 = (uint32_t)((PORTB_PCR2 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTB_PCR3: ISF=0,MUX=1 */
  PORTB_PCR3 = (uint32_t)((PORTB_PCR3 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTB_PCR4: ISF=0,MUX=1 */
  PORTB_PCR4 = (uint32_t)((PORTB_PCR4 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTB_PCR5: ISF=0,MUX=1 */
  PORTB_PCR5 = (uint32_t)((PORTB_PCR5 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTB_PCR6: ISF=0,MUX=1 */
  PORTB_PCR6 = (uint32_t)((PORTB_PCR6 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTB_PCR7: ISF=0,MUX=1 */
  PORTB_PCR7 = (uint32_t)((PORTB_PCR7 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTB_PCR9: ISF=0,MUX=1 */
  PORTB_PCR9 = (uint32_t)((PORTB_PCR9 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTB_PCR20: ISF=0,MUX=1 */
  PORTB_PCR20 = (uint32_t)((PORTB_PCR20 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTB_PCR22: ISF=0,MUX=1 */
  PORTB_PCR22 = (uint32_t)((PORTB_PCR22 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTC_PCR18: ISF=0,IRQC=9,MUX=1 */
  PORTC_PCR18 = (uint32_t)((PORTC_PCR18 & (uint32_t)~0x01060600UL) | (uint32_t)0x00090100UL);
  /* PORTC_DFCR: CS=0 */
  PORTC_DFCR &= (uint32_t)~0x01UL;                      
  /* PORTC_DFWR: FILT=0 */
  PORTC_DFWR &= (uint32_t)~0x1FUL;                      
  /* PORTC_PCR0: ISF=0,MUX=1 */
  PORTC_PCR0 = (uint32_t)((PORTC_PCR0 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTC_PCR2: ISF=0,MUX=1 */
  PORTC_PCR2 = (uint32_t)((PORTC_PCR2 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTC_PCR3: ISF=0,MUX=1 */
  PORTC_PCR3 = (uint32_t)((PORTC_PCR3 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTC_PCR8: ISF=0,MUX=1 */
  PORTC_PCR8 = (uint32_t)((PORTC_PCR8 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTC_PCR10: ISF=0,MUX=1 */
  PORTC_PCR10 = (uint32_t)((PORTC_PCR10 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTC_PCR12: ISF=0,MUX=1 */
  PORTC_PCR12 = (uint32_t)((PORTC_PCR12 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTC_PCR13: ISF=0,MUX=1 */
  PORTC_PCR13 = (uint32_t)((PORTC_PCR13 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTC_PCR15: ISF=0,MUX=1 */
  PORTC_PCR15 = (uint32_t)((PORTC_PCR15 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTC_PCR17: ISF=0,MUX=1 */
  PORTC_PCR17 = (uint32_t)((PORTC_PCR17 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTC_PCR19: ISF=0,MUX=1 */
  PORTC_PCR19 = (uint32_t)((PORTC_PCR19 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTD_DFCR: CS=0 */
  PORTD_DFCR &= (uint32_t)~0x01UL;                      
  /* PORTD_DFWR: FILT=0 */
  PORTD_DFWR &= (uint32_t)~0x1FUL;                      
  /* PORTD_PCR6: ISF=0,MUX=1 */
  PORTD_PCR6 = (uint32_t)((PORTD_PCR6 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTD_PCR10: ISF=0,MUX=1 */
  PORTD_PCR10 = (uint32_t)((PORTD_PCR10 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTD_PCR12: ISF=0,MUX=1 */
  PORTD_PCR12 = (uint32_t)((PORTD_PCR12 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTD_PCR14: ISF=0,MUX=1 */
  PORTD_PCR14 = (uint32_t)((PORTD_PCR14 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTE_DFCR: CS=0 */
  PORTE_DFCR &= (uint32_t)~0x01UL;                      
  /* PORTE_DFWR: FILT=0 */
  PORTE_DFWR &= (uint32_t)~0x1FUL;                      
  /* PORTE_PCR28: ISF=0,MUX=1 */
  PORTE_PCR28 = (uint32_t)((PORTE_PCR28 & (uint32_t)~0x01000600UL) | (uint32_t)0x0100UL);
  /* PORTB_PCR17: ISF=0,MUX=2 */
  PORTB_PCR17 = (uint32_t)((PORTB_PCR17 & (uint32_t)~0x01000500UL) | (uint32_t)0x0200UL);
  /* PORTB_PCR16: ISF=0,MUX=2 */
  PORTB_PCR16 = (uint32_t)((PORTB_PCR16 & (uint32_t)~0x01000500UL) | (uint32_t)0x0200UL);
  /* PORTB_PCR11: ISF=0,MUX=2 */
  PORTB_PCR11 = (uint32_t)((PORTB_PCR11 & (uint32_t)~0x01000500UL) | (uint32_t)0x0200UL);
  /* PORTB_PCR10: ISF=0,MUX=2 */
  PORTB_PCR10 = (uint32_t)((PORTB_PCR10 & (uint32_t)~0x01000500UL) | (uint32_t)0x0200UL);
  /* PORTD_PCR2: ISF=0,MUX=3 */
  PORTD_PCR2 = (uint32_t)((PORTD_PCR2 & (uint32_t)~0x01000400UL) | (uint32_t)0x0300UL);
  /* PORTD_PCR3: ISF=0,MUX=3 */
  PORTD_PCR3 = (uint32_t)((PORTD_PCR3 & (uint32_t)~0x01000400UL) | (uint32_t)0x0300UL);
  /* NVICISER1: SETENA|=0x00020000 */
  NVICISER1 |= (uint32_t)0x00020000UL;                       
  /* ### Init_FTM init code */
  /* SIM_SCGC6: FTM0=1 */
  SIM_SCGC6 |= 0x01000000UL;                                 
  (void)(FTM0_SC == 0U);               /* Dummy read of the FTM0_SC register to clear the interrupt flag */
  /* FTM0_SC: TOF=0,TOIE=0,CPWMS=0,CLKS=0,PS=0 */
  FTM0_SC = 0x00UL;                    /* Stop the counter */
  (void)(FTM0_C4SC == 0U);             /* Dummy read of the FTM0_C4SC register to clear the interrupt flag */
  /* FTM0_MODE: WPDIS=1 */
  FTM0_MODE |= 0x04UL;                 /* Disable write protection */
  /* FTM0_MODE: FTMEN=0 */
  FTM0_MODE &= (unsigned long int)~0x01UL;             
  /* FTM0_COMBINE: FAULTEN3=0,SYNCEN3=0,DTEN3=0,COMP3=0,FAULTEN2=0,SYNCEN2=0,DTEN2=0,DECAPEN2=0,COMP2=0,COMBINE2=0,FAULTEN1=0,SYNCEN1=0,DTEN1=0,COMP1=0,FAULTEN0=0,SYNCEN0=0,DTEN0=0,COMP0=0 */
  FTM0_COMBINE &= (unsigned long int)~0x72777272UL;             
  /* FTM0_INVCTRL: INV3EN=0,INV2EN=0,INV1EN=0,INV0EN=0 */
  FTM0_INVCTRL &= (unsigned long int)~0x0FUL;             
  /* FTM0_C0SC: CHF=0,MSB=0,MSA=0,ELSB=0,ELSA=0 */
  FTM0_C0SC &= (unsigned long int)~0xFFFFFFBEUL;             
  /* FTM0_C1SC: CHF=0,MSB=0,MSA=0,ELSB=0,ELSA=0 */
  FTM0_C1SC &= (unsigned long int)~0xFFFFFFBEUL;             
  /* FTM0_C2SC: CHF=0,MSB=0,MSA=0,ELSB=0,ELSA=0 */
  FTM0_C2SC &= (unsigned long int)~0xFFFFFFBEUL;             
  /* FTM0_C3SC: CHF=0,MSB=0,MSA=0,ELSB=0,ELSA=0 */
  FTM0_C3SC &= (unsigned long int)~0xFFFFFFBEUL;             
  /* FTM0_C4SC: CHF=0,CHIE=0,MSB=1,ELSB=0,ELSA=1,DMA=0 */
  FTM0_C4SC = (FTM0_C4SC & (unsigned long int)~0xFFFFFFCBUL) | 0x24UL;
  /* FTM0_C5SC: CHF=0,MSB=0,MSA=0,ELSB=0,ELSA=0 */
  FTM0_C5SC &= (unsigned long int)~0xFFFFFFBEUL;             
  /* FTM0_C6SC: CHF=0,MSB=0,MSA=0,ELSB=0,ELSA=0 */
  FTM0_C6SC &= (unsigned long int)~0xFFFFFFBEUL;             
  /* FTM0_C7SC: CHF=0,MSB=0,MSA=0,ELSB=0,ELSA=0 */
  FTM0_C7SC &= (unsigned long int)~0xFFFFFFBEUL;             
  /* FTM0_C4V: VAL=0x04E1 */
  FTM0_C4V = 0x04E1UL;                            
  /* FTM0_OUTINIT:  */
  FTM0_OUTINIT &= (unsigned long int)~0xFFFFFF00UL;             
  /* FTM0_FLTCTRL: FFVAL=0 */
  FTM0_FLTCTRL &= (unsigned long int)~0x0F00UL;             
  /* FTM0_FLTPOL: FLT3POL=0,FLT2POL=0,FLT1POL=0,FLT0POL=0 */
  FTM0_FLTPOL &= (unsigned long int)~0x0FUL;             
  /* FTM0_FLTCTRL: FFLTR3EN=0,FFLTR2EN=0,FFLTR1EN=0,FFLTR0EN=0,FAULT3EN=0,FAULT2EN=0,FAULT1EN=0,FAULT0EN=0 */
  FTM0_FLTCTRL &= (unsigned long int)~0xFFUL;             
  /* FTM0_SYNC: SWSYNC=0,TRIG2=0,TRIG1=0,TRIG0=0,SYNCHOM=0,REINIT=0,CNTMAX=0,CNTMIN=0 */
  FTM0_SYNC &= (unsigned long int)~0xFFUL;             
  /* FTM0_EXTTRIG: INITTRIGEN=0,CH1TRIG=0,CH0TRIG=0,CH5TRIG=0,CH4TRIG=0,CH3TRIG=0,CH2TRIG=0 */
  FTM0_EXTTRIG &= (unsigned long int)~0x7FUL;             
  /* FTM0_MOD: MOD=0x09C3 */
  FTM0_MOD = (FTM0_MOD & (unsigned long int)~0xF63CUL) | 0x09C3UL;
  /* FTM0_CNTIN: INIT=0 */
  FTM0_CNTIN &= (unsigned long int)~0xFFFFUL;             
  /* FTM0_DEADTIME: DTPS=0,DTVAL=0 */
  FTM0_DEADTIME &= (unsigned long int)~0xFFUL;             
  /* FTM0_CNT: COUNT=0 */
  FTM0_CNT &= (unsigned long int)~0xFFFFUL;             
  /* FTM0_MODE: FAULTIE=0,FAULTM=0,PWMSYNC=0,INIT=1,FTMEN=0 */
  FTM0_MODE = (FTM0_MODE & (unsigned long int)~0xFFFFFFE9UL) | 0x02UL;
  /* FTM0_SYNCONF: SYNCMODE=0,SWOC=0,INVC=0,CNTINC=0,HWTRIGMODE=0 */
  FTM0_SYNCONF &= (unsigned long int)~0xFFE0E0FFUL;             
  /* FTM0_SC: TOF=0,TOIE=0,CPWMS=0,CLKS=1,PS=0 */
  FTM0_SC = (FTM0_SC & (unsigned long int)~0xF7UL) | 0x08UL;
  /* FTM0_FMS: FAULTF=0,WPEN=0,FAULTF3=0,FAULTF2=0,FAULTF1=0,FAULTF0=0 */
  FTM0_FMS &= (unsigned long int)~0xCFUL;             
  /* FTM0_SWOCTRL: CH4OC=0 */
  FTM0_SWOCTRL &= (unsigned long int)~0x10UL;             
  /* FTM0_CONF: GTBEOUT=0,GTBEEN=0,BDMMODE=0,NUMTOF=0 */
  FTM0_CONF &= (unsigned long int)~0x06DFUL;             
  /* FTM0_PWMLOAD: LDOK=0,CH7SEL=0,CH6SEL=0,CH5SEL=0,CH4SEL=1,CH3SEL=0,CH2SEL=0,CH1SEL=0,CH0SEL=0 */
  FTM0_PWMLOAD = (FTM0_PWMLOAD & (unsigned long int)~0x02EFUL) | 0x10UL;
  /* ### Init_FTM init code */
  /* SIM_SCGC6: FTM1=1 */
  SIM_SCGC6 |= 0x02000000UL;                                 
  (void)(FTM1_SC == 0U);               /* Dummy read of the FTM1_SC register to clear the interrupt flag */
  /* FTM1_SC: TOF=0,TOIE=0,CPWMS=0,CLKS=0,PS=0 */
  FTM1_SC = 0x00UL;                    /* Stop the counter */
  (void)(FTM1_C0SC == 0U);             /* Dummy read of the FTM1_C0SC register to clear the interrupt flag */
  (void)(FTM1_C1SC == 0U);             /* Dummy read of the FTM1_C1SC register to clear the interrupt flag */
  /* FTM1_MODE: WPDIS=1 */
  FTM1_MODE |= 0x04UL;                 /* Disable write protection */
  /* FTM1_MODE: FTMEN=0 */
  FTM1_MODE &= (unsigned long int)~0x01UL;             
  /* FTM1_INVCTRL: INV0EN=0 */
  FTM1_INVCTRL &= (unsigned long int)~0x01UL;             
  /* FTM1_COMBINE: FAULTEN0=0,SYNCEN0=0,DTEN0=0,DECAPEN0=0,COMP0=0,COMBINE0=0 */
  FTM1_COMBINE &= (unsigned long int)~0x77UL;             
  /* FTM1_C0SC: CHF=0,CHIE=0,MSB=1,ELSB=1,ELSA=0,DMA=0 */
  FTM1_C0SC = (FTM1_C0SC & (unsigned long int)~0xFFFFFFC7UL) | 0x28UL;
  /* FTM1_C1SC: CHF=0,CHIE=0,MSB=1,ELSB=1,ELSA=0,DMA=0 */
  FTM1_C1SC = (FTM1_C1SC & (unsigned long int)~0xFFFFFFC7UL) | 0x28UL;
  /* FTM1_C0V: VAL=0xDF50 */
  FTM1_C0V = 0xDF50UL;                            
  /* FTM1_C1V: VAL=0xE2D6 */
  FTM1_C1V = 0xE2D6UL;                            
  /* FTM1_FILTER: CH1FVAL=0,CH0FVAL=0 */
  FTM1_FILTER &= (unsigned long int)~0xFFUL;             
  /* FTM1_OUTINIT:  */
  FTM1_OUTINIT &= (unsigned long int)~0xFFFFFF00UL;             
  /* FTM1_FLTCTRL: FFVAL=0 */
  FTM1_FLTCTRL &= (unsigned long int)~0x0F00UL;             
  /* FTM1_FLTPOL: FLT2POL=0,FLT1POL=0,FLT0POL=0 */
  FTM1_FLTPOL &= (unsigned long int)~0x07UL;             
  /* FTM1_FLTCTRL: FFLTR2EN=0,FFLTR1EN=0,FFLTR0EN=0,FAULT2EN=0,FAULT1EN=0,FAULT0EN=0 */
  FTM1_FLTCTRL &= (unsigned long int)~0x77UL;             
  /* FTM1_SYNC: SWSYNC=0,TRIG2=0,TRIG1=0,TRIG0=0,SYNCHOM=0,REINIT=0,CNTMAX=0,CNTMIN=0 */
  FTM1_SYNC &= (unsigned long int)~0xFFUL;             
  /* FTM1_EXTTRIG: INITTRIGEN=0,CH1TRIG=0,CH0TRIG=0 */
  FTM1_EXTTRIG &= (unsigned long int)~0x70UL;             
  /* FTM1_MOD: MOD=0xF423 */
  FTM1_MOD = (FTM1_MOD & (unsigned long int)~0x0BDCUL) | 0xF423UL;
  /* FTM1_CNTIN: INIT=0 */
  FTM1_CNTIN &= (unsigned long int)~0xFFFFUL;             
  /* FTM1_DEADTIME: DTPS=0,DTVAL=0 */
  FTM1_DEADTIME &= (unsigned long int)~0xFFUL;             
  /* FTM1_CNT: COUNT=0 */
  FTM1_CNT &= (unsigned long int)~0xFFFFUL;             
  /* FTM1_MODE: FAULTIE=0,FAULTM=0,PWMSYNC=0,INIT=1,FTMEN=0 */
  FTM1_MODE = (FTM1_MODE & (unsigned long int)~0xFFFFFFE9UL) | 0x02UL;
  /* FTM1_SYNCONF: SYNCMODE=0,SWOC=0,INVC=0,CNTINC=0,HWTRIGMODE=0 */
  FTM1_SYNCONF &= (unsigned long int)~0xFFE0E0FFUL;             
  /* FTM1_SC: TOF=0,TOIE=0,CPWMS=0,CLKS=1,PS=4 */
  FTM1_SC = (FTM1_SC & (unsigned long int)~0xF3UL) | 0x0CUL;
  /* FTM1_FMS: FAULTF=0,WPEN=0,FAULTF3=0,FAULTF2=0,FAULTF1=0,FAULTF0=0 */
  FTM1_FMS &= (unsigned long int)~0xCFUL;             
  /* FTM1_QDCTRL: PHAFLTREN=0,PHBFLTREN=0,PHAPOL=0,PHBPOL=0,QUADMODE=0,QUADIR=0,TOFDIR=0,QUADEN=0 */
  FTM1_QDCTRL = 0x00UL;                            
  /* FTM1_SWOCTRL: CH1OC=0,CH0OC=0 */
  FTM1_SWOCTRL &= (unsigned long int)~0x03UL;             
  /* FTM1_CONF: GTBEOUT=0,GTBEEN=0,BDMMODE=0,NUMTOF=0 */
  FTM1_CONF &= (unsigned long int)~0x06DFUL;             
  /* FTM1_PWMLOAD: LDOK=0,CH1SEL=1,CH0SEL=1 */
  FTM1_PWMLOAD = (FTM1_PWMLOAD & (unsigned long int)~0x0200UL) | 0x03UL;
  /* ### Init_LPTMR init code */
  /* SIM_SCGC5: LPTIMER=1 */
  SIM_SCGC5 |= 0x01UL;                                 
  /* LPTMR0_CSR: TCF=1,TIE=0,TPS=0,TPP=0,TFC=0,TMS=0,TEN=0 */
  LPTMR0_CSR = 0x80UL;                            
  /* LPTMR0_CMR: COMPARE=0xFFFF */
  LPTMR0_CMR = 0xFFFFUL;                            
  /* LPTMR0_CSR: TCF=1,TIE=0,TPS=2,TPP=0,TFC=1,TMS=1,TEN=0 */
  LPTMR0_CSR = 0xA6UL;                            
  /* LPTMR0_PSR: PRESCALE=0,PBYP=1,PCS=3 */
  LPTMR0_PSR = 0x07UL;                            
  /* LPTMR0_CSR: TCF=0,TEN=0 */
  LPTMR0_CSR &= (unsigned long int)~0x81UL;             
  /* ### Init_PIT init code */
  /* SIM_SCGC6: PIT=1 */
  SIM_SCGC6 |= 0x00800000UL;                                 
  /* PIT_MCR: MDIS=0,FRZ=0 */
  PIT_MCR = 0x00UL;                            
  /* PIT_TFLG0: TIF=1 */
  PIT_TFLG0 = 0x01UL;                            
  /* PIT_TFLG1: TIF=1 */
  PIT_TFLG1 = 0x01UL;                            
  /* PIT_TFLG2: TIF=1 */
  PIT_TFLG2 = 0x01UL;                            
  /* PIT_TFLG3: TIF=1 */
  PIT_TFLG3 = 0x01UL;                            
  /* PIT_LDVAL0: TSV=0x0007A120 */
  PIT_LDVAL0 = 0x0007A120UL;                            
  /* PIT_LDVAL1: TSV=0x000F4240 */
  PIT_LDVAL1 = 0x000F4240UL;                            
  /* PIT_LDVAL2: TSV=0xC350 */
  PIT_LDVAL2 = 0xC350UL;                            
  /* PIT_LDVAL3: TSV=0 */
  PIT_LDVAL3 = 0x00UL;                            
  /* PIT_TCTRL0: TIE=1,TEN=0 */
  PIT_TCTRL0 = 0x02UL;                            
  /* PIT_TCTRL1: TIE=1,TEN=0 */
  PIT_TCTRL1 = 0x02UL;                            
  /* PIT_TCTRL2: TIE=1,TEN=0 */
  PIT_TCTRL2 = 0x02UL;                            
  /* PIT_TCTRL3: TIE=0,TEN=0 */
  PIT_TCTRL3 = 0x00UL;                            
  /* PIT_TCTRL0: TEN=1 */
  PIT_TCTRL0 |= 0x01UL;                                 
  /* PIT_TCTRL1: TEN=1 */
  PIT_TCTRL1 |= 0x01UL;                                 
  /* PIT_TCTRL2: TEN=1 */
  PIT_TCTRL2 |= 0x01UL;                                 
  /* ### Init_GPIO init code */
  /* GPIOA_PDDR: PDD&=~0x3C00,PDD|=0x1403C000 */
  GPIOA_PDDR = (GPIOA_PDDR & (unsigned long int)~0x3C00UL) | 0x1403C000UL;
  /* ### Init_GPIO init code */
  /* GPIOB_PSOR: PTSO&=~0x0200 */
  GPIOB_PSOR &= (unsigned long int)~0x0200UL;             
  /* GPIOB_PCOR: PTCO|=0x0200 */
  GPIOB_PCOR |= 0x0200UL;                                 
  /* GPIOB_PDDR: PDD&=~0xFF,PDD|=0x00500200 */
  GPIOB_PDDR = (GPIOB_PDDR & (unsigned long int)~0xFFUL) | 0x00500200UL;
  /* ### Init_GPIO init code */
  /* GPIOC_PSOR: PTSO|=0x1400 */
  GPIOC_PSOR |= 0x1400UL;                                 
  /* GPIOC_PCOR: PTCO&=~0x1400 */
  GPIOC_PCOR &= (unsigned long int)~0x1400UL;             
  /* GPIOC_PDDR: PDD&=~0x00040000,PDD|=0x000AB50D */
  GPIOC_PDDR = (GPIOC_PDDR & (unsigned long int)~0x00040000UL) | 0x000AB50DUL;
  /* ### Init_GPIO init code */
  /* GPIOD_PSOR: PTSO|=0x5400 */
  GPIOD_PSOR |= 0x5400UL;                                 
  /* GPIOD_PCOR: PTCO&=~0x5400 */
  GPIOD_PCOR &= (unsigned long int)~0x5400UL;             
  /* GPIOD_PDDR: PDD|=0x5440 */
  GPIOD_PDDR |= 0x5440UL;                                 
  /* ### Init_GPIO init code */
  /* GPIOE_PSOR: PTSO|=0x10000000 */
  GPIOE_PSOR |= 0x10000000UL;                                 
  /* GPIOE_PCOR: PTCO&=~0x10000000 */
  GPIOE_PCOR &= (unsigned long int)~0x10000000UL;             
  /* GPIOE_PDDR: PDD|=0x10000000 */
  GPIOE_PDDR |= 0x10000000UL;                                 
  /* ### Init_SPI init code */
  /* SIM_SCGC6: SPI1=1 */
  SIM_SCGC6 |= 0x2000UL;                                 
  /* SPI1_MCR: MSTR=0,CONT_SCKE=0,DCONF=0,FRZ=0,MTFE=0,PCSSE=0,ROOE=0,PCSIS=0,DOZE=0,MDIS=0,DIS_TXF=0,DIS_RXF=0,CLR_TXF=0,CLR_RXF=0,SMPL_PT=0,HALT=1 */
  SPI1_MCR = 0x01UL;                            
  /* SPI1_MCR: MSTR=1,CONT_SCKE=0,DCONF=0,FRZ=0,MTFE=0,PCSSE=0,ROOE=0,PCSIS=1,DOZE=0,MDIS=0,DIS_TXF=0,DIS_RXF=0,CLR_TXF=1,CLR_RXF=1,SMPL_PT=0,HALT=1 */
  SPI1_MCR = 0x80010C01UL;                            
  /* SPI1_TCR: SPI_TCNT=0 */
  SPI1_TCR = 0x00UL;                            
  /* SPI1_CTAR0: DBR=0,FMSZ=7,CPOL=0,CPHA=0,LSBFE=0,PCSSCK=2,PASC=2,PDT=2,PBR=2,CSSCK=7,ASC=6,DT=7,BR=8 */
  SPI1_CTAR0 = 0x38AA7678UL;                            
  /* SPI1_CTAR1: DBR=0,FMSZ=0x0F,CPOL=0,CPHA=0,LSBFE=0,PCSSCK=0,PASC=0,PDT=0,PBR=0,CSSCK=0,ASC=0,DT=0,BR=0 */
  SPI1_CTAR1 = 0x78000000UL;                            
  /* SPI1_SR: TCF=1,TXRXS=0,EOQF=1,TFUF=1,TFFF=1,RFOF=1,RFDF=1,TXCTR=0,TXNXTPTR=0,RXCTR=0,POPNXTPTR=0 */
  SPI1_SR = 0x9A0A0000UL;                            
  /* SPI1_RSER: TCF_RE=0,EOQF_RE=0,TFUF_RE=0,TFFF_RE=0,TFFF_DIRS=0,RFOF_RE=0,RFDF_RE=0,RFDF_DIRS=0 */
  SPI1_RSER = 0x00UL;                            
  /* ### Init_UART init code */
  /* SIM_SCGC4: UART2=1 */
  SIM_SCGC4 |= 0x1000UL;                                 
  /* UART2_C2: TE=0,RE=0 */
  UART2_C2 &= (unsigned char)~(unsigned char)0x0CU;                     
  /* UART2_BDH: LBKDIE=0,RXEDGIE=0,SBR=0 */
  UART2_BDH = 0x00U;                                      
  /* UART2_BDL: SBR=0x1B */
  UART2_BDL = 0x1BU;                                      
  /* UART2_MA1: MA=0 */
  UART2_MA1 = 0x00U;                                      
  /* UART2_MA2: MA=0 */
  UART2_MA2 = 0x00U;                                      
  /* UART2_C4: MAEN1=0,MAEN2=0,M10=0,BRFA=4 */
  UART2_C4 = 0x04U;                                      
  /* UART2_C1: LOOPS=0,UARTSWAI=0,RSRC=0,M=0,WAKE=0,ILT=0,PE=0,PT=0 */
  UART2_C1 = 0x00U;                                      
  /* UART2_S2: LBKDIF=1,RXEDGIF=1,MSBF=0,RXINV=0,RWUID=0,BRK13=0,LBKDE=0,RAF=0 */
  UART2_S2 = 0xC0U;                                      
  /* UART2_MODEM: RXRTSE=0,TXRTSPOL=0,TXRTSE=0,TXCTSE=0 */
  UART2_MODEM = 0x00U;                                      
  /* UART2_IR: IREN=0,TNP=0 */
  UART2_IR = 0x00U;                                      
  /* UART2_TWFIFO: TXWATER=0 */
  UART2_TWFIFO = 0x00U;                                      
  /* UART2_RWFIFO: RXWATER=1 */
  UART2_RWFIFO = 0x01U;                                      
  /* UART2_SFIFO: TXEMPT=0,RXEMPT=0,TXOF=1,RXUF=1 */
  UART2_SFIFO = 0x03U;                                      
  /* UART2_CFIFO: TXFLUSH=1,RXFLUSH=1,TXOFE=0,RXUFE=0 */
  UART2_CFIFO = 0xC0U;                                      
  /* UART2_PFIFO: TXFE=0,RXFE=0 */
  UART2_PFIFO &= (unsigned char)~(unsigned char)0x88U;                     
  (void) UART2_S1;                     /* Dummy read of the UART2_S1 register to clear flags */
  (void) UART2_D;                      /* Dummy read of the UART2_D register to clear flags */
  /* UART2_C5: TDMAS=0,RDMAS=0 */
  UART2_C5 = 0x00U;                                      
  /* UART2_C3: R8=0,T8=0,TXDIR=0,TXINV=0,ORIE=0,NEIE=0,FEIE=0,PEIE=0 */
  UART2_C3 = 0x00U;                                      
  /* UART2_C2: TIE=0,TCIE=0,RIE=1,ILIE=0,TE=1,RE=1,RWU=0,SBK=0 */
  UART2_C2 = 0x2CU;                                      
  /* ### */
  Cpu_SetBASEPRI(0U);
} /* MCU_init */


/*
** ===================================================================
**     Interrupt handler : isr_default
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
PE_ISR(isr_default)
{
  /* Write your interrupt code here ... */

}
/* end of isr_default */


/*
** ===================================================================
**     Interrupt handler : isrINT_NMI
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
PE_ISR(isrINT_NMI)
{
  /* Write your interrupt code here ... */

}
/* end of isrINT_NMI */


/*
** ===================================================================
**     Interrupt handler : isrINT_SPI1
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
PE_ISR(isrINT_SPI1)
{
  /* Write your interrupt code here ... */

}
/* end of isrINT_SPI1 */


/*
** ===================================================================
**     Interrupt handler : isrINT_UART2_RX_TX
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
PE_ISR(isrINT_UART2_RX_TX)
{
  /* Write your interrupt code here ... */
	UART2_S1 &= UART_S1_RDRF_MASK;
	uart_ReceiveData();
}
/* end of isrINT_UART2_RX_TX */


/*
** ===================================================================
**     Interrupt handler : isrINT_UART2_ERR
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
PE_ISR(isrINT_UART2_ERR)
{
  /* Write your interrupt code here ... */

}
/* end of isrINT_UART2_ERR */


/*
** ===================================================================
**     Interrupt handler : isrINT_FTM0
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
PE_ISR(isrINT_FTM0)
{
  /* Write your interrupt code here ... */

}
/* end of isrINT_FTM0 */


/*
** ===================================================================
**     Interrupt handler : isrINT_FTM1
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
PE_ISR(isrINT_FTM1)
{
  /* Write your interrupt code here ... */

}
/* end of isrINT_FTM1 */


/*
** ===================================================================
**     Interrupt handler : isrINT_PIT0
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
PE_ISR(isrINT_PIT0)
{
  /* Write your interrupt code here ... */
	PIT_TFLG0 = 1;
	keyboard_TimerKeyPressed();
}
/* end of isrINT_PIT0 */


/*
** ===================================================================
**     Interrupt handler : isrINT_PIT1
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
PE_ISR(isrINT_PIT1)
{
  /* Write your interrupt code here ... */
	//measure speed
	PIT_TFLG1 = 1;
	ClockSpeedControl();
}
/* end of isrINT_PIT1 */


/*
** ===================================================================
**     Interrupt handler : isrINT_PIT2
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
PE_ISR(isrINT_PIT2)
{
  /* Write your interrupt code here ... */
	PIT_TFLG2 = 1;
	IntegralClock();
}
/* end of isrINT_PIT2 */


/*
** ===================================================================
**     Interrupt handler : isrINT_PIT3
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
PE_ISR(isrINT_PIT3)
{
  /* Write your interrupt code here ... */
	PIT_TFLG3 = 1;
}
/* end of isrINT_PIT3 */


/*
** ===================================================================
**     Interrupt handler : isrINT_LPTimer
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
PE_ISR(isrINT_LPTimer)
{
  /* Write your interrupt code here ... */

}
/* end of isrINT_LPTimer */


/*
** ===================================================================
**     Interrupt handler : isrINT_PORTA
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
PE_ISR(isrINT_PORTA)
{
  /* Write your interrupt code here ... */
	PORTA_ISFR |= PORT_ISFR_ISF(13); //clear the flag
	//scan_keyboard();
	//keyboard_InputClose();
}
/* end of isrINT_PORTA */


/*
** ===================================================================
**     Interrupt handler : isrINT_PORTC
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
PE_ISR(isrINT_PORTC)
{
  /* Write your interrupt code here ... */
	PORTC_ISFR |= PORT_ISFR_ISF(18);
	ov7620_FlagVSYNC();
}
/* end of isrINT_PORTC */



#ifdef __cplusplus
extern "C" {
#endif
extern uint32_t __SP_INIT[];
extern void __thumb_startup( void );
#ifdef __cplusplus
}
#endif

/* Interrupt vector table */
#ifndef UNASSIGNED_ISR
  #define UNASSIGNED_ISR isr_default   /* unassigned interrupt service routine */
#endif


/* Pragma to place the interrupt vector table on correct location  location defined in linker file. */
#pragma define_section vectortable ".vectortable" ".vectortable" ".vectortable" far_abs R
static __declspec(vectortable) tVectorTable __vect_table = { /* Interrupt vector table */
   __SP_INIT,                                              /* 0 (0x00000000) (prior: -) */
  {
   (tIsrFunc)&__thumb_startup,                             /* 1 (0x00000004) (prior: -) */
   (tIsrFunc)&isrINT_NMI,                                  /* 2 (0x00000008) (prior: -2) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 3 (0x0000000C) (prior: -1) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 4 (0x00000010) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 5 (0x00000014) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 6 (0x00000018) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 7 (0x0000001C) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 8 (0x00000020) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 9 (0x00000024) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 10 (0x00000028) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 11 (0x0000002C) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 12 (0x00000030) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 13 (0x00000034) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 14 (0x00000038) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 15 (0x0000003C) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 16 (0x00000040) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 17 (0x00000044) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 18 (0x00000048) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 19 (0x0000004C) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 20 (0x00000050) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 21 (0x00000054) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 22 (0x00000058) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 23 (0x0000005C) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 24 (0x00000060) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 25 (0x00000064) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 26 (0x00000068) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 27 (0x0000006C) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 28 (0x00000070) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 29 (0x00000074) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 30 (0x00000078) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 31 (0x0000007C) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 32 (0x00000080) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 33 (0x00000084) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 34 (0x00000088) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 35 (0x0000008C) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 36 (0x00000090) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 37 (0x00000094) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 38 (0x00000098) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 39 (0x0000009C) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 40 (0x000000A0) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 41 (0x000000A4) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 42 (0x000000A8) (prior: -) */
   (tIsrFunc)&isrINT_SPI1,                                 /* 43 (0x000000AC) (prior: 0) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 44 (0x000000B0) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 45 (0x000000B4) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 46 (0x000000B8) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 47 (0x000000BC) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 48 (0x000000C0) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 49 (0x000000C4) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 50 (0x000000C8) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 51 (0x000000CC) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 52 (0x000000D0) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 53 (0x000000D4) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 54 (0x000000D8) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 55 (0x000000DC) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 56 (0x000000E0) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 57 (0x000000E4) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 58 (0x000000E8) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 59 (0x000000EC) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 60 (0x000000F0) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 61 (0x000000F4) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 62 (0x000000F8) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 63 (0x000000FC) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 64 (0x00000100) (prior: -) */
   (tIsrFunc)&isrINT_UART2_RX_TX,                          /* 65 (0x00000104) (prior: 3) */
   (tIsrFunc)&isrINT_UART2_ERR,                            /* 66 (0x00000108) (prior: 0) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 67 (0x0000010C) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 68 (0x00000110) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 69 (0x00000114) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 70 (0x00000118) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 71 (0x0000011C) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 72 (0x00000120) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 73 (0x00000124) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 74 (0x00000128) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 75 (0x0000012C) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 76 (0x00000130) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 77 (0x00000134) (prior: -) */
   (tIsrFunc)&isrINT_FTM0,                                 /* 78 (0x00000138) (prior: 0) */
   (tIsrFunc)&isrINT_FTM1,                                 /* 79 (0x0000013C) (prior: 0) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 80 (0x00000140) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 81 (0x00000144) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 82 (0x00000148) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 83 (0x0000014C) (prior: -) */
   (tIsrFunc)&isrINT_PIT0,                                 /* 84 (0x00000150) (prior: 8) */
   (tIsrFunc)&isrINT_PIT1,                                 /* 85 (0x00000154) (prior: 3) */
   (tIsrFunc)&isrINT_PIT2,                                 /* 86 (0x00000158) (prior: 4) */
   (tIsrFunc)&isrINT_PIT3,                                 /* 87 (0x0000015C) (prior: 0) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 88 (0x00000160) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 89 (0x00000164) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 90 (0x00000168) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 91 (0x0000016C) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 92 (0x00000170) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 93 (0x00000174) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 94 (0x00000178) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 95 (0x0000017C) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 96 (0x00000180) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 97 (0x00000184) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 98 (0x00000188) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 99 (0x0000018C) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 100 (0x00000190) (prior: -) */
   (tIsrFunc)&isrINT_LPTimer,                              /* 101 (0x00000194) (prior: 0) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 102 (0x00000198) (prior: -) */
   (tIsrFunc)&isrINT_PORTA,                                /* 103 (0x0000019C) (prior: 6) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 104 (0x000001A0) (prior: -) */
   (tIsrFunc)&isrINT_PORTC,                                /* 105 (0x000001A4) (prior: 4) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 106 (0x000001A8) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 107 (0x000001AC) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 108 (0x000001B0) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 109 (0x000001B4) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 110 (0x000001B8) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 111 (0x000001BC) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 112 (0x000001C0) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 113 (0x000001C4) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 114 (0x000001C8) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 115 (0x000001CC) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 116 (0x000001D0) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 117 (0x000001D4) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR,                              /* 118 (0x000001D8) (prior: -) */
   (tIsrFunc)&UNASSIGNED_ISR                               /* 119 (0x000001DC) (prior: -) */
  }
};



/* END MCUinit */

/*
** ###################################################################
**
**     This file was created by Processor Expert 5.1 [04.49]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
